- name: Idempotence
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create dir
    ansible.builtin.file:
      path: /tmp/foo
      state: directory
  - name: echo
    ansible.builtin.command:
      cmd: echo fail
