---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: localhost
  gather_facts: true # no idea what else to assert over
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
